/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../components/ui/button/Button.vue')['default']
    Card: typeof import('./../components/ui/card/Card.vue')['default']
    CardContent: typeof import('./../components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./../components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./../components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./../components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./../components/ui/card/CardTitle.vue')['default']
    Cart: typeof import('./../components/Cart.vue')['default']
    CartButton: typeof import('./../components/CartButton.vue')['default']
    Icon: typeof import('@iconify/vue')['Icon']
    MainLayout: typeof import('./../layouts/MainLayout.vue')['default']
    ModeButton: typeof import('./../components/ModeButton.vue')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    NumberField: typeof import('./../components/ui/number-field/NumberField.vue')['default']
    NumberFieldContent: typeof import('./../components/ui/number-field/NumberFieldContent.vue')['default']
    NumberFieldDecrement: typeof import('./../components/ui/number-field/NumberFieldDecrement.vue')['default']
    NumberFieldIncrement: typeof import('./../components/ui/number-field/NumberFieldIncrement.vue')['default']
    NumberFieldInput: typeof import('./../components/ui/number-field/NumberFieldInput.vue')['default']
    ProductCard: typeof import('./../components/ProductCard.vue')['default']
    ProductList: typeof import('./../components/ProductList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./../components/ui/skeleton/Skeleton.vue')['default']
    SkeletonCard: typeof import('./../components/SkeletonCard.vue')['default']
    SkeletonImage: typeof import('./../components/SkeletonImage.vue')['default']
    SkeletonLoader: typeof import('./../components/SkeletonLoader.vue')['default']
    Toast: typeof import('./../components/ui/toast/Toast.vue')['default']
    ToastAction: typeof import('./../components/ui/toast/ToastAction.vue')['default']
    ToastClose: typeof import('./../components/ui/toast/ToastClose.vue')['default']
    ToastDescription: typeof import('./../components/ui/toast/ToastDescription.vue')['default']
    Toaster: typeof import('./../components/ui/toast/Toaster.vue')['default']
    ToastProvider: typeof import('./../components/ui/toast/ToastProvider.vue')['default']
    ToastTitle: typeof import('./../components/ui/toast/ToastTitle.vue')['default']
    ToastViewport: typeof import('./../components/ui/toast/ToastViewport.vue')['default']
  }
}
